name: Runners Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed
      - requested

env:
  PAT: ${{ secrets.PAT }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  GOOGLE_CREDENTIALS: ${{ secrets.GCE_SA_KEY }}
  GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
  PULUMI_STACK_NAME: ${{ github.event.workflow_run.id }}
  GS_BUCKET: ${{ secrets.GS_BUCKET }}
  RUNNER_REPO: pavlovic-ivan/ephemeral-github-runner-gcp

jobs:
  deploy-runners:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'requested' }}
    environment: cuda-test-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload config
        uses: actions/upload-artifact@v2
        with:
          name: pulumi-config
          path: config.yaml
          retention-days: 1

      - name: Checkout Pulumi Ephemeral Github Runner project
        uses: actions/checkout@v2
        with:
          repository: $RUNNER_REPO
          ref: main

      - name: Download config
        uses: actions/upload-artifact@v2
        with:
          name: pulumi-config

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Execute Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          npm install
          pulumi login $GS_BUCKET
          pulumi stack init -s $PULUMI_STACK_NAME
          pulumi up --diff --config-file config.yaml -y

  destroy-runners:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'completed' }}
    environment: cuda-test-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload config
        uses: actions/upload-artifact@v2
        with:
          name: pulumi-config
          path: config.yaml
          retention-days: 1

      - name: Checkout Pulumi Ephemeral Github Runner project
        uses: actions/checkout@v2
        with:
          repository: $RUNNER_REPO
          ref: main

      - name: Download config
        uses: actions/upload-artifact@v2
        with:
          name: pulumi-config

      - name: Execute Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          npm install
          pulumi login $GS_BUCKET
          pulumi stack select $PULUMI_STACK_NAME
          pulumi destroy --config-file config.yaml -y
          pulumi stack rm $PULUMI_STACK_NAME -y