name: Runners Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed
      - requested

env:
  PAT: ${{ secrets.PAT }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  GOOGLE_CREDENTIALS: ${{ secrets.GCE_SA_KEY }}
  GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
  PULUMI_STACK_NAME: ilgpu_${{ github.event.workflow_run.id }}
  GS_BUCKET: ${{ secrets.GS_BUCKET }}

jobs:
  is-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Check if repo is upstream
        id: is-upstream
        run: |
          fork=$(gh api repos/${{ github.repository }} | jq .fork)
          upstream=false
          [[ $fork == "false" ]] && upstream=true
          echo "::set-output name=upstream::$upstream"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      upstream: ${{ steps.is-upstream.outputs.upstream }}
  deploy-runners:
    runs-on: ubuntu-latest
    needs: is-upstream
    if: ${{ github.event.action == 'requested' && needs.is-upstream.outputs.upstream }}
    environment: cuda-test-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Pulumi Ephemeral Github Runner project
        uses: actions/checkout@v2
        with:
          repository: pavlovic-ivan/ephemeral-github-runner-gcp
          ref: main
          path: pulumi

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

# pulumi up --diff --config-file ../ILGPU-fork2/config.yaml -y
      - name: Execute Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          npm install
          pulumi login $GS_BUCKET
          pulumi stack init -s $PULUMI_STACK_NAME
          pulumi up --diff --config-file ./config.yaml

  # destroy-runners:
  #   runs-on: ubuntu-latest
  #   needs: is-upstream
  #   if: ${{ github.event.action == 'completed' && needs.is-upstream.outputs.upstream }}
  #   environment: cuda-test-infra
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Checkout Pulumi Ephemeral Github Runner project
  #       uses: actions/checkout@v2
  #       with:
  #         repository: pavlovic-ivan/ephemeral-github-runner-gcp
  #         ref: main
  #         path: 

  #     - name: Execute Pulumi
  #       run: |
  #         curl -fsSL https://get.pulumi.com | sh
  #         npm install
  #         pulumi login $GS_BUCKET
  #         pulumi stack select $PULUMI_STACK_NAME
  #         pulumi destroy --config-file artifacts/config.yaml -y
  #         pulumi stack rm $PULUMI_STACK_NAME -y